isolates:
  {{isolates}}
min_contig_size:
  {{min_contig_size}}
min_contigs:
  {{min_contigs}}
chewieCPU:
  {{cpu}}
schemaPath:
  {{schemPath}}
data_type:
  {{data_type}}
assembler:
  {{assembler}}
workdir:
  {{workdir}}
